build:
	g++ main.c my-first-lib.h -o prog
	echo "Done! You can test a program via 'make test' or write your own commands! :D"
clean:
	rm -f ./prog
test:
	./prog 1 101
	./prog 2 3
	./prog 3 1
	./prog 4 1
	./prog 5 13
	./prog 5 14
	./prog 6 1234
	./prog 7 1331
	./prog 7 133
	./prog 8 1 100
	./prog 9 36 48
	./prog 10 24 36