buildAndTestNode:
	clear && echo "Lab by Azer Sadykhzadeh :)\n\n" && gcc testNode.c node.c -o node && ./node && echo "Finished!"
buildAndTestArray:
	clear && echo "Lab by Azer Sadykhzadeh :)\n\n" && gcc testArray.c array.c -o array && ./array && echo "Finished!"
clean:
	rm node && rm array && echo "Done :)"