buildAndTestCopy:
	clear && echo "Lab by Azer Sadykhzadeh :)\n\n" && gcc copyFile.c -o copy && ./copy copyFile.c helloWorld.c && echo "Finished! :D"
buildAndTestHT:
	clear && echo "Lab by Azer Sadykhzadeh :)\n\n" && gcc headAndTail.c -o ht && ./ht ./headAndTail.c h 10 && echo "====" && ./ht ./headAndTail.c t 10 && echo "Finished!"
clean:
	rm copy ht helloWorld.c && echo "Done :)"